#ifndef PROJEKT_ZALICZENOWY__LAB_MARIA_BRODOWSKA_PRODUKTY_H
#define PROJEKT_ZALICZENOWY__LAB_MARIA_BRODOWSKA_PRODUKTY_H

class Produkt{

};


#endif //PROJEKT_ZALICZENOWY__LAB_MARIA_BRODOWSKA_PRODUKTY_H
